#workDirect = "/home/users1/jhsim/Dropbox/src/TB_DMFT/TB+DMFT14.3/add_on_script/mem_matrix_julia/DataMaker/T_40"
inputFile = "Giw_Lorentzian.full.dat2"

NumOrbit = 1
num_of_subblock = 1
N_Matsubara  =  1500
inverse_temp =  100.0

EwinOuterRight =   15.0
EwinInnerRight =   10.0
EwinInnerLeft =   -10.0
EwinOuterLeft =   -15.0
coreWindow   = 2
coreDense    = 10

Egrid =  50

offDiagonal = true     #true, false
auxiliary_inverse_temp_range = [0.5e-3, 1000.0]
auxTempRenomalFactorInitial = 1.01

NumIter = 20000
mixingInitial =  0.05
mixing_max =     0.1
mixing_min =     1e-7
pulay_mixing_start =       1
pulay_mixing_step =        1    ## negative for stable, simple-mixing-like behavior
pulay_mixing_history =     20     ##1 forsimpleMixing
